[package]
name = "magicube-play"
version.workspace = true
edition.workspace = true
publish = false
default-run = "magicube-play"

[dependencies]
crossterm.workspace = true
directories.workspace = true
magicube-solver = { path = "../.." }
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
magicube-solver = { path = "../.." }
